variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'eprprnmanagefacade'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprprnmanagefacaderepository'
  serviceName: 'prdrwdwebwa1420'
